name: ClojureScriptCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  test_cljs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run cljs test
      run: lein cljs:test
    # TODO: Run a clojurescript app

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: ci
        SLACK_FOOTER: Cookie! Om nom nom nom
        SLACK_ICON: https://avatars3.githubusercontent.com/u/10654370?size=48
        SLACK_USERNAME: Cookie Monster
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
