name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    executor: browser-tools/default
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 85.0.4183.102
      - run:
          command: |
            google-chrome --version
          name: Check install
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run clj test
      run: lein test
    - name: Run cljs test
      run: lein fig:test

orbs:
  browser-tools: circleci/browser-tools@x.y
version: 2.1
