name: ClojureScriptCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_cljs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run cljs test
      run: lein cljs:test
    # TODO: Run a clojurescript app
