name: ClojureCI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test_clj:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run clj test
      run: lein test
    # TODO: Run a clojure app

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: ci
        SLACK_TITLE: Nom Nom Nom... Actions was triggered
        SLACK_ICON: https://avatars3.githubusercontent.com/u/10654370?size=48
        SLACK_USERNAME: Cookie Monster
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
