name: ClojureCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  test_clj:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run clj test
      run: lein test
    # TODO: Run a clojure app

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: ci
        SLACK_FOOTER: Cookie! Om nom nom nom
        SLACK_TITLE: 'All cool. More COOKIES! :cookie: :cookie:'
        SLACK_ICON: https://s.yimg.com/ny/api/res/1.2/5V_4ZnbeUOIWX0jvzJi4qQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTcwNTtoPTM5Ni41NjI1/https://s.yimg.com/uu/api/res/1.2/zsjOo16W1oVnGpxtwqZJEA--~B/aD0yMjU7dz00MDA7c209MTthcHBpZD15dGFjaHlvbg--/http://media.zenfs.com/en-US/homerun/hello_giggles_454/f060aa1119b1aa41ae7ed5a0678ec581
        SLACK_USERNAME: Cookie Monster
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Slack Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: ci
        SLACK_FOOTER: Cookie! Om nom nom nom
        SLACK_TITLE: 'It Failed! No cookies. :cry:'
        SLACK_ICON: https://s.yimg.com/ny/api/res/1.2/5V_4ZnbeUOIWX0jvzJi4qQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTcwNTtoPTM5Ni41NjI1/https://s.yimg.com/uu/api/res/1.2/zsjOo16W1oVnGpxtwqZJEA--~B/aD0yMjU7dz00MDA7c209MTthcHBpZD15dGFjaHlvbg--/http://media.zenfs.com/en-US/homerun/hello_giggles_454/f060aa1119b1aa41ae7ed5a0678ec581
        SLACK_USERNAME: Cookie Monster
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
